# Oauth
oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: "http://13.209.66.8:8080/login/oauth2/code/kakao"

  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: "http://13.209.66.8:8080/login/oauth2/code/naver"