spring:
  profiles:
    active: local, production
    include: oauth

  # DB
  datasource:
    url: ${DB_JDBC_URL}?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  # Redis
  redis:
    data:
      redis:
        port: 6379
        host: redis

server: ${PRODUCTION_SERVER_URL}

# JWT
jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-milliseconds: 86400000
  refresh-token-validity-in-milliseconds: 2592000000

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enable : true
  cache:
    disabled : true
  use-fqn: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8